<?php
include 'db.php';

// جلب المراكز
$centers = $conn->query("SELECT * FROM centers");

// جلب المرشحين
$candidates = $conn->query("SELECT * FROM candidates");

// جلب المحطات التي تحتوي على أصوات
$votes = [];
$votes_result = $conn->query("SELECT station_id FROM votes GROUP BY station_id");

while ($vote = $votes_result->fetch_assoc()) {
    $votes[] = $vote['station_id'];
    }

    if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['add_vote'])) {
        $station_id = $_POST['station_id'];
            $candidate_id = $_POST['candidate_id'];
                $vote_count = $_POST['vote_count'];

                    // التحقق من وجود الأصوات لهذا المرشح في المحطة المحددة
                        $sql_check = "SELECT * FROM votes WHERE station_id = '$station_id' AND candidate_id = '$candidate_id'";
                            $result_check = $conn->query($sql_check);

                                if ($result_check->num_rows > 0) {
                                        // إذا كان السجل موجودًا، نقوم بتحديث الأصوات
                                                $sql_update = "UPDATE votes SET vote_count = '$vote_count' WHERE station_id = '$station_id' AND candidate_id = '$candidate_id'";
                                                        $conn->query($sql_update);
                                                                echo "<p style='color: green;'>تم تحديث الأصوات بنجاح!</p>";
                                                                    } else {
                                                                            // إذا لم يكن السجل موجودًا، نقوم بإضافة السجل الجديد
                                                                                    $sql_insert = "INSERT INTO votes (station_id, candidate_id, vote_count) VALUES ('$station_id', '$candidate_id', '$vote_count')";
                                                                                            $conn->query($sql_insert);
                                                                                                    echo "<p style='color: green;'>تم إضافة الأصوات بنجاح!</p>";
                                                                                                        }
                                                                                                        }
                                                                                                        ?>

                                                                                                        <!DOCTYPE html>
                                                                                                        <html lang="ar">
                                                                                                        <head>
                                                                                                            <meta charset="UTF-8">
                                                                                                                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                                                    <title>إضافة الأصوات</title>
                                                                                                                        <link rel="stylesheet" href="style.css">
                                                                                                                            <style>
                                                                                                                                    .green { background-color: #90ee90; } /* اللون الأخضر للمحطات التي تحتوي على أصوات */
                                                                                                                                        </style>
                                                                                                                                        </head>
                                                                                                                                        <body>

                                                                                                                                        <h1>إضافة الأصوات</h1>

                                                                                                                                        <form method="POST">
                                                                                                                                            <label for="center_id">اختر المركز:</label>
                                                                                                                                                <select name="center_id" id="center_id" required>
                                                                                                                                                        <option value="">اختر مركز</option>
                                                                                                                                                                <?php while ($row = $centers->fetch_assoc()) { ?>
                                                                                                                                                                            <option value="<?php echo $row['id']; ?>"><?php echo $row['name']; ?></option>
                                                                                                                                                                                    <?php } ?>
                                                                                                                                                                                        </select><br>

                                                                                                                                                                                            <label for="station_id">اختر المحطة:</label>
                                                                                                                                                                                                <select name="station_id" id="station_id" required>
                                                                                                                                                                                                        <option value="">اختر محطة</option>
                                                                                                                                                                                                            </select><br>

                                                                                                                                                                                                                <label for="candidate_id">اختر المرشح:</label>
                                                                                                                                                                                                                    <select name="candidate_id" id="candidate_id" required>
                                                                                                                                                                                                                            <option value="">اختر مرشح</option>
                                                                                                                                                                                                                                    <?php while ($row = $candidates->fetch_assoc()) { ?>
                                                                                                                                                                                                                                                <option value="<?php echo $row['id']; ?>"><?php echo $row['name']; ?></option>
                                                                                                                                                                                                                                                        <?php } ?>
                                                                                                                                                                                                                                                            </select><br>

                                                                                                                                                                                                                                                                <label for="vote_count">عدد الأصوات:</label>
                                                                                                                                                                                                                                                                    <input type="number" name="vote_count" required><br>

                                                                                                                                                                                                                                                                        <button type="submit" name="add_vote">إضافة الأصوات</button>
                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                        <!-- زر الرجوع إلى الصفحة الرئيسية -->
                                                                                                                                                                                                                                                                        <div class="return-btn">
                                                                                                                                                                                                                                                                            <a href="index.php"><button>الرجوع إلى الصفحة الرئيسية</button></a>
                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                            <script>
                                                                                                                                                                                                                                                                                // دالة لتحديث المحطات عند اختيار المركز
                                                                                                                                                                                                                                                                                    document.getElementById('center_id').addEventListener('change', function() {
                                                                                                                                                                                                                                                                                            var centerId = this.value;
                                                                                                                                                                                                                                                                                                    var stationSelect = document.getElementById('station_id');

                                                                                                                                                                                                                                                                                                            // إعادة تعيين المحطات
                                                                                                                                                                                                                                                                                                                    stationSelect.innerHTML = '<option value="">اختر محطة</option>';

                                                                                                                                                                                                                                                                                                                            if (centerId) {
                                                                                                                                                                                                                                                                                                                                        // إرسال طلب لجلب المحطات من الخادم
                                                                                                                                                                                                                                                                                                                                                    var xhr = new XMLHttpRequest();
                                                                                                                                                                                                                                                                                                                                                                xhr.open('GET', 'get_stations.php?center_id=' + centerId, true);
                                                                                                                                                                                                                                                                                                                                                                            xhr.onreadystatechange = function() {
                                                                                                                                                                                                                                                                                                                                                                                            if (xhr.readyState == 4 && xhr.status == 200) {
                                                                                                                                                                                                                                                                                                                                                                                                                var stations = JSON.parse(xhr.responseText);
                                                                                                                                                                                                                                                                                                                                                                                                                                    stations.forEach(function(station) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            var option = document.createElement('option');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    option.value = station.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            option.textContent = 'محطة ' + station.station_number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // إضافة اللون الأخضر إذا تم إضافة أصوات لهذه المحطة من قبل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (<?php echo json_encode($votes); ?>.includes(station.id)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                option.classList.add('green');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                stationSelect.appendChild(option);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            xhr.send();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </html>